[package]
name = "sonar_sweep"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"

[[bin]]
name = "sonar_sweep"
path = "src/main.rs"
